set -g @catppuccin_flavor 'macchiato'

run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux

set -g status-left ""
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] session: #S '
set -g status-right-length 100
