"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 2000
format = """$time$directory$character"""
right_format = """$all"""

[azure]
disabled = false
format = "[$symbol($username: $subscription)]($style) "

[character]
success_symbol = '[➜](bold green)'

#[direnv]
#disabled = false

[git_branch]
format = '[$symbol$branch]($style) '

[terraform]
format = 'via [$symbol$version $workspace]($style) '

[time]
disabled = false
format = '[$time]($style) '
time_format = '%H:%M'

