"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 2000
format = """
$directory\
$fill\
$all\
$direnv\
$git_state\
$git_branch\
$line_break\
$time\
$character
"""

[azure]
disabled = false
format = '[$symbol($username: $subscription)]($style) '

[character]
success_symbol = '[➜](bold green)'

[direnv]
disabled = false
symbol = ''
format = '[$symbol $loaded]($style) '
loaded_msg = '✓'
unloaded_msg = 'x'

[fill]
symbol = ' '

[git_branch]
format = '[$symbol$branch]($style) '

[git_status]
disabled = true

[line_break]
disabled = false

[nodejs]
format = '[$symbol($version)]($style) '

[package]
disabled = true

[terraform]
format = '[$symbol$version $workspace]($style) '

[time]
disabled = false
format = '[$time]($style) '
time_format = '%H:%M'
